### PR TITLE
Sync wrappers with underlying contracts

### PR DESCRIPTION
**Pull request by ermyas**

### CODE REVIEW

**Comment by ricardolyn** [comment]
Note: it might be good for the future to remove generated code from the repo and automatically do it as part of the build

**Comment by ermyas** [comment]
I agree

**Comment by drinkcoffee** [comment]
However, then when people clone the repo to view the code, their IDE will complain with lots of static analysis errors, as source code won't exist. This will lead some people to conclude that the code in the repo is broken.

**Comment by ermyas** [comment]
I don't think that will be too much of an issue. 
Our ReadMe can indicate that you need to run a Gradle build (or at least trigger the generator task), which isn't an uncommon practice, so I don't imagine most people will be stumped by this. However, at the moment our Gradle build triggers both unit and integration tests, the latter of which requires a test network to have been spun up apriori and takes a fair bit of time to execute. This makes things a bit more onerous for a person that just wants to explore the codebase. The solution to this, however, I think is a combination of a) separating the running of our integration tests from the standard build task, and b) using hardhat to minimise the overheads of the test network.

**Pull request merged**
